import './globals.css';
import NextAuthProvider from './context/SessionContext';
import Nav from '@/app/components/Nav';
import { getServerSession } from 'next-auth/next';
import authOptions from '@/libs/authOptions';
import Hydrate from '@/app/components/Hydrate';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className="mx-64">
        <NextAuthProvider>
          <Hydrate>
            <Nav user={session?.user} expires={session?.expires as string} />
            {children}
          </Hydrate>
        </NextAuthProvider>
      </body>
    </html>
  );
}
