import './globals.css';
import NextAuthProvider from '@/context/SessionContext';
import Nav from '@/components/Nav';
import { auth } from '@/libs/authOptions';
import Hydrate from '@/components/Hydrate';
import { Roboto } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`mx-4 lg:mx-48 ${roboto.className}`}>
        <NextAuthProvider>
          <Hydrate>
            <Nav user={session?.user!} expires={session?.expires as string} />
            {children}
          </Hydrate>
        </NextAuthProvider>
      </body>
    </html>
  );
}
